<?php


namespace App\Http\Resources\PaperTopic;


use Illuminate\Http\Resources\Json\JsonResource;

class PaperTopicPageResource extends JsonResource
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}