<?php


namespace App\Models;


use App\Scopes\CreatedByScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Models\PaperModel
 *
 * @property int $id
 * @property string $title 考卷标题
 * @property string $front_cover 考卷封面
 * @property int $paper_type_id 考卷类型ID
 * @property int $answer_number 答题人数
 * @property int $topic_number 题目数量
 * @property int $status 考卷状态
 * @property string $description 考卷说明
 * @property int $created_by 创建人
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string|null $deleted_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel whereAnswerNumber($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel whereCreatedBy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel whereFrontCover($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel wherePaperTypeId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel whereTopicNumber($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel whereUpdatedAt($value)
 * @mixin \Eloquent
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\PaperModel whereDescription($value)
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\PaperModel onlyTrashed()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\PaperModel withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\PaperModel withoutTrashed()
 */
class PaperModel extends Model
{
    use SoftDeletes;

    protected $table = 'paper';
    protected $fillable = [
        'title',
        'front_cover',
        'paper_type_id',
        'answer_number',
        'topic_number',
        'status',
        'description',
        'created_by',
    ];
    protected $casts = [
        'media'  => 'array',
        'option' => 'array',
        'answer' => 'array',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new CreatedByScope());
    }
}